### ISSUE TITLE
Ask questions

### ISSUE THREAD

**Issue by cdata123** [amandaberg/TIRcolorization#1]
Hello, our lab is also researching color processing. I am very interested in the articles you published. I downloaded the source code on github. I want to ask if the code on github is missing a data set. npy file? If so, can you provide the .npy file on your side? thank you very much

**Comment by amandaberg** [comment]
Hello! Sorry for the late reply. I have added some info about the .npy files in the readme. I preprocessed the input images to speed up the processing time, hence, the .npy files. The functions that I used are included in utils.py (generate_image_data and generate_image_lab_data), please find some more info in the readme.
